apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo
  labels:
    app: hugo
spec:
  selector:
    matchLabels:
      app: hugo
  template:
    metadata:
      labels:
        app: hugo
    spec:
      # imagePullSecrets:
      #   - name: dockerhub-secret # Use this if you need to pull images from a private Docker registry
      containers:
      - name: hugo
        image: ynos999/hugo-dezool:latest
        ports:
        - containerPort: 1313  # jāatbilst EXPOSE no Dockerfile