apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hugo-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: dezool.db.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hugo
            port:
              number: 80